apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hugo-site.fullname" . }}-nginx
  labels:
    {{- include "hugo-site.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen {{ .Values.containerPorts.http }};
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location = /healthz {
        access_log off;
        return 200 'ok';
        add_header Content-Type text/plain;
      }
    }

    server {
      listen {{ .Values.containerPorts.status }};
      server_name 127.0.0.1 localhost;

      location /nginx_status {
        stub_status;
        access_log off;
        allow 127.0.0.1;
        deny all;
      }
    }
