apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hugo-site.fullname" . }}
  labels:
    {{- include "hugo-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hugo-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hugo-site.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
              protocol: TCP
            - name: status
              containerPort: {{ .Values.containerPorts.status }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: nginx-prometheus-exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          args:
            - -nginx.scrape-uri=http://127.0.0.1:{{ .Values.containerPorts.status }}/nginx_status
          ports:
            - name: metrics
              containerPort: {{ .Values.containerPorts.metrics }}
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "hugo-site.fullname" . }}-nginx
